sudo: false
env: RELEASE_TESTING=1
language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
matrix:
  include:
    - perl: 5.28
      env: COVERAGE=1   # enables coverage+coveralls reporting
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto      
install:
  - cpan-install --deps
  - cpan-install --coverage

